services:
    nginx:
        image: nginx:alpine
        container_name: ${NGINX_CONTAINER_NAME}
        ports:
            - ${NGINX_HTTP_PORT}:80
        restart: unless-stopped
        volumes:
            - ${NGINX_DOCUMENT_ROOT_PATH}:/var/www/html:z,ro
            - ${NGINX_DEFAULT_CONFIG_PATH}:/etc/nginx/conf.d/default.conf:ro
        networks:
            - homelab
    php:
        image: php:8.3-fpm-alpine
        container_name: php-fpm
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ${NGINX_DOCUMENT_ROOT_PATH}:/var/www/html
        networks:
            - homelab
        command: >
            sh -c "
              if [ ! -x /usr/local/bin/composer ]; then
                curl -sS https://getcomposer.org/installer | php &&
                mv composer.phar /usr/local/bin/composer;
              fi;
              [ -f composer.json ] && composer install;
              php-fpm
            "

networks:
    homelab:
        external: true
