services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - ${NGINX_DEFAULT_CONFIG_PATH}:/etc/nginx/nginx.conf:ro
    networks:
      - homelab

networks:
  homelab:
    external: true