services:
    db:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        networks:
            - homelab
        volumes:
            - ${MYSQL_VOLUME_PATH}/db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    nextcloud:
        image: nextcloud:latest
        container_name: nextcloud
        restart: unless-stopped
        networks:
            - homelab
        ports:
            - 8080:80
        volumes:
            - ${NEXTCLOUD_DATA_PATH}/html:/var/www/html
        environment:
            - MYSQL_HOST=db
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - NEXTCLOUD_TRUSTED_DOMAIN=${NEXTCLOUD_TRUSTED_DOMAIN}
            - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
            - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
        depends_on:
            - db

networks:
    homelab:
        external: true
