version: '3.9'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ${NEXTCLOUD_DATA}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ${NEXTCLOUD_DATA}/html:/var/www/html
      - /mnt/cloud/backups/iphone:/var/www/html/data/iphone/files
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    depends_on:
      - db

networks:
  homelab:
    external: true
