version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ${MYSQL_DATA_PATH}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

networks:
  homelab:
    external: true
