services:
    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        restart: "unless-stopped"
        user: 1000:0
        environment:
            - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHED_SERVER_URL}
        networks:
            - homelab
        ports:
            - 8081:80
            - 8096:8096
            - 8920:8920
        volumes:
            - ${JELLYFIN_CONFIG_FOLDER_PATH}:/config
            - ${JELLYFIN_CACHE_FOLDER_PATH}:/cache
            - type: bind
              source: ${JELLYFIN_MOVIES_FOLDER_SOURCE}
              target: /movies
              read_only: true
            - type: bind
              source: ${JELLYFIN_TVSHOWS_FOLDER_SOURCE}
              target: /tvshows
              read_only: true
networks:
    homelab:
        external: true
